//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCards.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CardDetail
    {
        public string CardNo { get; set; }
        public string Expiry { get; set; }
    }
    public partial class ValidateResult
    {
        public string Result { get; set; }
        public string CardType { get; set; }
    }
}
